import DescriptionRoundedIcon from "@mui/icons-material/DescriptionRounded";
import { Card, CardContent, Chip, Divider, Grid, List, ListItem, ListItemIcon, ListItemText, Stack, Typography } from "@mui/material";

import { HistoricalReportsChart } from "../components/widgets/HistoricalReportsChart";
import { KpiCard } from "../components/widgets/KpiCard";
import { PassFailureChart } from "../components/widgets/PassFailureChart";
import { ValidationTrendChart } from "../components/widgets/ValidationTrendChart";

const kpis = [
  { label: "Validations Executed", value: "1,274", delta: "+12% this week", trend: "up" as const },
  { label: "Pass %", value: "97.4%", delta: "+0.9%", trend: "up" as const },
  { label: "Failure %", value: "2.6%", delta: "-0.9%", trend: "down" as const },
  { label: "Historical Reports", value: "428", delta: "+36 new", trend: "up" as const },
];

const trendData = [
  { week: "W1", passRate: 94.1, failures: 34 },
  { week: "W2", passRate: 95.2, failures: 28 },
  { week: "W3", passRate: 96.4, failures: 22 },
  { week: "W4", passRate: 97.4, failures: 16 },
  { week: "W5", passRate: 97.1, failures: 19 },
  { week: "W6", passRate: 97.8, failures: 14 },
];

const historicalReportData = [
  { month: "Jan", reports: 52 },
  { month: "Feb", reports: 61 },
  { month: "Mar", reports: 58 },
  { month: "Apr", reports: 67 },
  { month: "May", reports: 79 },
  { month: "Jun", reports: 85 },
];

const latestReports = [
  { name: "AMEX_Daily_Migration_Validation", status: "Ready" },
  { name: "SNOW_Weekly_Integrity_Check", status: "Ready" },
  { name: "Billing_Pipeline_Reconciliation", status: "Generating" },
  { name: "Salesforce_Opportunity_Audit", status: "Ready" },
];

export function OverviewPage(): React.JSX.Element {
  return (
    <Stack spacing={2.5}>
      <Grid container spacing={2.2}>
        {kpis.map((kpi) => (
          <Grid key={kpi.label} size={{ xs: 12, sm: 6, lg: 3 }}>
            <KpiCard label={kpi.label} value={kpi.value} delta={kpi.delta} trend={kpi.trend} />
          </Grid>
        ))}
      </Grid>

      <Grid container spacing={2.2}>
        <Grid size={{ xs: 12, lg: 8 }}>
          <Card>
            <CardContent>
              <ValidationTrendChart data={trendData} />
            </CardContent>
          </Card>
        </Grid>
        <Grid size={{ xs: 12, lg: 4 }}>
          <Card>
            <CardContent>
              <PassFailureChart pass={97.4} failure={2.6} />
            </CardContent>
          </Card>
        </Grid>
      </Grid>

      <Grid container spacing={2.2}>
        <Grid size={{ xs: 12, lg: 7 }}>
          <Card>
            <CardContent>
              <HistoricalReportsChart data={historicalReportData} />
            </CardContent>
          </Card>
        </Grid>
        <Grid size={{ xs: 12, lg: 5 }}>
          <Card>
            <CardContent>
              <Stack spacing={1.6}>
                <Typography variant="h6">Recent Historical Reports</Typography>
                <Typography variant="body2" color="text.secondary">
                  Latest downloadable report artifacts generated by scheduled validation workflows.
                </Typography>
                <Divider />
                <List disablePadding>
                  {latestReports.map((report) => (
                    <ListItem key={report.name} disableGutters sx={{ py: 0.9 }}>
                      <ListItemIcon sx={{ minWidth: 36 }}>
                        <DescriptionRoundedIcon fontSize="small" color="primary" />
                      </ListItemIcon>
                      <ListItemText
                        primary={report.name}
                        secondary="JSON, HTML, PDF"
                        slotProps={{
                          primary: { variant: "body2", fontWeight: 600 },
                          secondary: { variant: "caption" },
                        }}
                      />
                      <Chip
                        label={report.status}
                        color={report.status === "Ready" ? "success" : "warning"}
                        size="small"
                        variant="outlined"
                      />
                    </ListItem>
                  ))}
                </List>
              </Stack>
            </CardContent>
          </Card>
        </Grid>
      </Grid>
    </Stack>
  );
}